add Volunteer model
NickGM23/PetFamily pull request #3
Opened 2024-08-25 21:50 UTC by NickGM23

2024-08-26 06:03 UTC, YADARAN1 requested changes

2024-08-26 06:03 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Models/Volunteer.cs
> +        public string Name { get; private set; } = string.Empty;
Лучше будет объединить Name и FIO в 1 класс

2024-08-27 07:36 UTC, YADARAN1 requested changes

2024-08-27 07:36 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Models/Shared/FullName.cs
> +        public string FirstName { get; init; } = string.Empty;
у VO только gett'еры, убрать init

2024-08-27 07:36 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Models/SocialNetwork.cs
> +        public string Name { get; private set; } = string.Empty;
Это тоже VO, private set убрать

2024-08-27 07:36 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Models/SocialNetwork.cs
> +    public class SocialNetwork
замени на record

2024-08-27 07:36 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Models/Volunteer.cs
> +    public class Volunteer : BaseModel
Что за BaseModel? Убрать наследование

2024-08-27 07:36 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Models/Volunteer.cs
> +        public IReadOnlyList<SocialNetwork> SocialNetworks => _socialNetworks;
Куда пропали ещё 2 листа с животными и реквизитами? Добавить

2024-08-27 09:55 UTC, NickGM23 commented on backend/src/PetFamily.Domain/Models/Shared/FullName.cs
> +        public string FirstName { get; init; } = string.Empty;
+

2024-08-27 09:55 UTC, NickGM23 commented on backend/src/PetFamily.Domain/Models/SocialNetwork.cs
> +        public string Name { get; private set; } = string.Empty;
++

2024-08-27 09:56 UTC, NickGM23 commented on backend/src/PetFamily.Domain/Models/SocialNetwork.cs
> +    public class SocialNetwork
++

2024-08-27 09:57 UTC, NickGM23 commented on backend/src/PetFamily.Domain/Models/Volunteer.cs
> +    public class Volunteer : BaseModel
Убрал BaseModel. Добавил Shared.Entity<Tid>

2024-08-27 09:59 UTC, NickGM23 commented on backend/src/PetFamily.Domain/Models/Volunteer.cs
> +        public IReadOnlyList<SocialNetwork> SocialNetworks => _socialNetworks;
Они не пропадали, они есть с 30 по 42 строку

2024-08-27 10:09 UTC, Asasen1 approved these changes

2024-08-27 10:09 UTC, Asasen1 commented on backend/src/PetFamily.Domain/Models/Pet.cs
>                                           string name,
ctrl+k+d

2024-08-27 10:15 UTC, merged